### ISSUE TITLE
TypeError is raised when comment field is left blank

### ISSUE THREAD

**Issue by jeremiah-c-leary** [jeremiah-c-leary/eda-log-file-warning-suppressor#12]
As the title says:

```yaml
     'ID':
        - msg: Some message
          comment:
          author: jcleary
```

Raises a `TypeError`

Need to handle this gracefully.
