### ISSUE TITLE
Multiply defined suppression rules are overwriting existing rules

### ISSUE THREAD

**Issue by jeremiah-c-leary** [jeremiah-c-leary/eda-log-file-warning-suppressor#7]
In the following suppression file:
```yaml
suppress:
   'ID1':
       - msg: some message
   'ID1':
       - msg: some other message
```

The first ID1 is dropped.

The desired behavior is they should be merged.

**Comment by jeremiah-c-leary** [comment]
The configuration is read by the pyYAML package, which I do not have any control over.  I really do not want to write my own parser to handle this.

**Comment by jeremiah-c-leary** [comment]
I think this is a solution:
```yaml
suppress:
    some-grouping-text:
      rules:
         'ID-1':
             - msg: some message
             - author: me
             - comment: some justification for rule
    some-other-grouping-text:
       rules:
          'ID-1':
              - msg: some other message
              - author: me
              - comment: some other justification for rule
```

the grouping text would be arbitrary. 
I would just walk the dictionary and look for the `rules` keyword.
This would allow for multiple levels of grouping.

This would also allow for setting other attributes above the rules if required.
